// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spid.Data;

#nullable disable

namespace Spid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611135642_AddHoraSolicitacaoViagem")]
    partial class AddHoraSolicitacaoViagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spid.Data.CentroCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CentrosCusto");
                });

            modelBuilder.Entity("Spid.Data.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Spid.Data.ConferenciaMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConfirmacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("CentroCustoId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("ConferenciasMensais");
                });

            modelBuilder.Entity("Spid.Data.EncerramentoMensal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLiberacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Encerrado")
                        .HasColumnType("bit");

                    b.Property<int?>("EncerradoPorId")
                        .HasColumnType("int");

                    b.Property<int?>("LiberadoPorId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncerradoPorId");

                    b.HasIndex("LiberadoPorId");

                    b.HasIndex("Ano", "Mes")
                        .IsUnique();

                    b.ToTable("EncerramentosMensais");
                });

            modelBuilder.Entity("Spid.Data.ImportacaoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeImportada")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ImportacoesLog");
                });

            modelBuilder.Entity("Spid.Data.ParceiroViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parceiros");
                });

            modelBuilder.Entity("Spid.Data.PerfilRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("Perfil", "RecursoId")
                        .IsUnique();

                    b.ToTable("PerfisRecurso");
                });

            modelBuilder.Entity("Spid.Data.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Spid.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<int>("ContadorAcessos")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTeste")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ponto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("Ponto")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Spid.Data.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Avaliacao")
                        .HasColumnType("int");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConferencia")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataViagem")
                        .HasColumnType("date");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("float");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly?>("HoraSolicitacao")
                        .HasColumnType("time(0)");

                    b.Property<string>("IdViagemParceiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoContestacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParceiroViagemId")
                        .HasColumnType("int");

                    b.Property<string>("StatusConferenciaGestor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorCotado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("IdViagemParceiro")
                        .IsUnique();

                    b.HasIndex("ParceiroViagemId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("Spid.Data.Colaborador", b =>
                {
                    b.HasOne("Spid.Data.CentroCusto", "CentroCusto")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCusto");
                });

            modelBuilder.Entity("Spid.Data.ConferenciaMensal", b =>
                {
                    b.HasOne("Spid.Data.CentroCusto", "CentroCusto")
                        .WithMany()
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spid.Data.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCusto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Spid.Data.EncerramentoMensal", b =>
                {
                    b.HasOne("Spid.Data.Usuario", "EncerradoPor")
                        .WithMany()
                        .HasForeignKey("EncerradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Spid.Data.Usuario", "LiberadoPor")
                        .WithMany()
                        .HasForeignKey("LiberadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EncerradoPor");

                    b.Navigation("LiberadoPor");
                });

            modelBuilder.Entity("Spid.Data.ImportacaoLog", b =>
                {
                    b.HasOne("Spid.Data.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Spid.Data.PerfilRecurso", b =>
                {
                    b.HasOne("Spid.Data.Recurso", "Recurso")
                        .WithMany("PerfisRecurso")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Spid.Data.Usuario", b =>
                {
                    b.HasOne("Spid.Data.CentroCusto", "CentroCusto")
                        .WithMany("Usuarios")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CentroCusto");
                });

            modelBuilder.Entity("Spid.Data.Viagem", b =>
                {
                    b.HasOne("Spid.Data.CentroCusto", "CentroCusto")
                        .WithMany("Viagens")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spid.Data.Colaborador", "Colaborador")
                        .WithMany("Viagens")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spid.Data.ParceiroViagem", "Parceiro")
                        .WithMany("Viagens")
                        .HasForeignKey("ParceiroViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroCusto");

                    b.Navigation("Colaborador");

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("Spid.Data.CentroCusto", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Usuarios");

                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("Spid.Data.Colaborador", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("Spid.Data.ParceiroViagem", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("Spid.Data.Recurso", b =>
                {
                    b.Navigation("PerfisRecurso");
                });
#pragma warning restore 612, 618
        }
    }
}
