// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spid.Data;

#nullable disable

namespace Spid.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224140955_AddSenhaHashToUsuario")]
    partial class AddSenhaHashToUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Spid.Data.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SetorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SetorId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Spid.Data.ParceiroViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parceiros");
                });

            modelBuilder.Entity("Spid.Data.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("Spid.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ponto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ponto")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Spid.Data.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Avaliacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataViagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("REAL");

                    b.Property<int?>("GestorResponsavelId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdViagemParceiro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoContestacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParceiroViagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusConferenciaGestor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusOrigem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorCotado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("GestorResponsavelId");

                    b.HasIndex("ParceiroViagemId");

                    b.HasIndex("SetorId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("Spid.Data.Colaborador", b =>
                {
                    b.HasOne("Spid.Data.Setor", "Setor")
                        .WithMany("Colaboradores")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Spid.Data.Viagem", b =>
                {
                    b.HasOne("Spid.Data.Colaborador", "Colaborador")
                        .WithMany("Viagens")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spid.Data.Usuario", "GestorResponsavel")
                        .WithMany()
                        .HasForeignKey("GestorResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Spid.Data.ParceiroViagem", "Parceiro")
                        .WithMany("Viagens")
                        .HasForeignKey("ParceiroViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spid.Data.Setor", "Setor")
                        .WithMany("Viagens")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("GestorResponsavel");

                    b.Navigation("Parceiro");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Spid.Data.Colaborador", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("Spid.Data.ParceiroViagem", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("Spid.Data.Setor", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
